# Generated by Django 4.1.6 on 2023-02-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expense_amounts_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amounts',
            new_name='amount',
        ),
    ]
